### ISSUE TITLE
Modify database

### ISSUE THREAD

**Issue by garcia1273** [ryanLungberg/CPW-212-Team-Project#10]
On CastList Table:
CastID should be an identity

On Movies Table:
CastID and AwardsID should be allowed to be null in order to be able to get option of saving a Movie/Show without having to add the cast or awards given.

**Comment by ryanLungberg** [comment]
I agree with your observations here. I will work on fixing the database and send you the updated copy as soon as possible. If I forget, remind me tomorrow in class!

**Comment by garcia1273** [comment]
Ryan,

can you let me know once you make the changes we talked about in class? thank you!!

**Comment by ryanLungberg** [comment]
Changes to the database have been made! Working on changing the add and remove behavior to reflect these changes.
