### ISSUE TITLE
Implement Add and Remove functionality for new version of MediaApplication

### ISSUE THREAD

**Issue by ryanLungberg** [ryanLungberg/CPW-212-Team-Project#7]
For this work on getting our Add and Remove buttons on the main form to work as intended. The current version of our project is in the ryan-1 branch, until I figure out how to merge it to master successfully.

**Comment by garcia1273** [comment]
Hey Ryan, 

I completed the Add part of the main form. I will work on the remove button next. I believe you should be able to see the changes I made in the master branch.

**Comment by garcia1273** [comment]
Hey Ryan, 
I am almost done with the Remove button function. I have not tested it yet, but I am confident I am going in the right direction.

**Comment by ryanLungberg** [comment]
Good to hear! I looked at the remove code you wrote and it looks pretty good! I will be able to test it out as well as the changes I made at school tomorrow and report back!

**Comment by garcia1273** [comment]
finally done
